language: bash

services:
  - docker

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

# matrix
env:
  - CORE=armhf PY=3.7.4
  - CORE=arm64 PY=3.7.4

script:
  - |
    sed -i "s/{CORE}/${CORE}/g" Python.Dockerfile && \
    cat Python.Dockerfile && \
    docker build . -f Python.Dockerfile -t multiarm-python:${CORE}-${PY} \
        --build-arg LOCAL_APT=no \
        --build-arg PY_VERSION=${PY}

# deploy:
#   provider: bash
#   script: docker_push
#   on:
#     branch: master