language: bash

services:
  - docker

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

# matrix
env:
  - CORE=armhf PY=3.7.4
  - CORE=arm64 PY=3.7.4

script:
  - bash build

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
